### ISSUE TITLE
Bag Sync Addon

### ISSUE THREAD

**Issue by MimPlays** [pereira-a/MBB#14]
I can't get the Bag Sync Addon to go into MBBR.

Thank you so much for your work on this project! You are a hero!

**Comment by pereira-a** [comment]
Issue resolved in this release https://github.com/pereira-a/MBB/releases/tag/4.0.14-release
![Wow_qqawD8Mvs9](https://user-images.githubusercontent.com/19942228/198895010-3a292a27-466b-40fe-9ce2-ec0a83301e73.png)
