### ISSUE TITLE
Icons outside of MBB

### ISSUE THREAD

**Issue by brokenbuddha** [pereira-a/MBB#17]
Hello, this is great and I really appreciate that you have taken the time to create such a useful and needed addon however it doesn't appear to work properly... there are several icons it appears to be incapable of detecting such as the button for AllTheThings and Detals!.

**Comment by pereira-a** [comment]
There seems to be no issue in collecting those buttons into the bag.
![image](https://user-images.githubusercontent.com/19942228/198895270-613473f9-ecbe-4155-900c-cc3f6cebba40.png)
