### ISSUE TITLE
Minimap buttons to ignore by default

### ISSUE THREAD

**Issue by eafurness** [pereira-a/MBB#20]
If it's not too much trouble, would you mind adding the following 3 items to the default ignore listing within MBB.lua ? If not ignored, they alter or interrupt functions of that addon. 

	[46] = "DugisArrowMinimapPoint1",  --Dugi Guides arrow
	[47] = "DugisArrowMinimapPoint2",  --Dugi Guides arrow
	[48] = "DugisArrowMinimapPoint3"  --Dugi Guides arrow

Thank  you very much for keeping this addon going!

Eric

**Comment by pereira-a** [comment]
Above buttons added to ignore list. 

New release to reflect these changes:
https://github.com/pereira-a/MBB/releases/tag/4.0.10-release
https://www.curseforge.com/wow/addons/minimapbuttonbag-reborn-mmb-reborn/files/4054216
